[pyprland]
plugins = ["scratchpads"]

[scratchpads.volume]
animation = "fromTop"
command = "pavucontrol"
class = "org.pulseaudio.pavucontrol"
size = "50% 50%"
margin = 42
multi = false

[scratchpads.drop-term]
animation = "fromTop"
command = "kitty --class drop-term"
class = "drop-term"
size = "75% 75%"
margin = 42
lazy = true
